# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  script:
   - npm prune
   - npm install
   - npm build

sut:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install -y rubygems
  - gem install dpl -v "=1.8.47"
  - dpl --provider=heroku --app=meweall-frontend --api-key=$HEROKU_SUT_API_KEY
  only:
  - master
